#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

while [ "$#" -gt 0 ]; do
  case "$1" in
  -a | --authorize-github)
    export AUTH_GITHUB=1
    shift 1
    ;;
  -p | --pull)
    pushd 
    git pull
    shift 1
    ;;
  *)
    echo " X Unknown option: $1"
    exit 1
    ;;
  esac
done

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
