$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 4
final_space: true
patch_pwsh_bleed: true
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: session
        style: plain
        foreground: '#ffffff'
        template: <p:struct>┏[</>{{ .UserName }}{{ if .SSHSession }}<p:struct>@</>{{ .HostName }}{{ end }}<p:struct>]</>
        cache:
          duration: 5m
          strategy: session
      - type: git
        style: plain
        foreground: '#ffffff'
        template: <p:struct>[</>{{ .HEAD }}<p:struct>]</>
        cache:
          duration: 2s
          strategy: session
      - type: root
        style: plain
        foreground: '#ffffff'
        template: <p:struct>[</><p:thndr></><p:struct>]</>
        cache:
          duration: 5m
          strategy: session
      - type: status
        style: plain
        foreground: '#ffffff'
        template: <p:struct>[x</>{{ reason .Code }}<p:struct>]</>
      - type: dotnet
        style: plain
        foreground: '#ffffff'
        template: <p:struct>[</>.NET {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }} <p:struct>]</>
        cache:
          duration: 168h
          strategy: folder
      - type: go
        style: plain
        foreground: '#ffffff'
        template: <p:struct>[</> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<p:struct>]</>
        cache:
          duration: 168h
          strategy: folder
      - type: node
        style: plain
        foreground: '#ffffff'
        template: <p:struct>[</> {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}<p:struct>]</>
        cache:
          duration: 168h
          strategy: folder
      - type: python
        style: plain
        foreground: '#ffffff'
        template: >-
          <p:struct>[</> {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end
          }}<p:struct>]</>
        cache:
          duration: 168h
          strategy: folder
      - type: rust
        style: plain
        foreground: '#ffffff'
        template: <p:struct>[</> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}<p:struct>]</>
        cache:
          duration: 168h
          strategy: folder
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: path
        style: plain
        foreground: '#ffffff'
        template: <p:struct>┖[</>{{ .Path }}<p:struct>]></>
        options:
          style: powerlevel
          max_width: 40
transient_prompt:
  template: '> '
  foreground: p:struct
  background: transparent
secondary_prompt:
  template: '>> '
  foreground: p:struct
palette:
  struct: '#CB4B16'
  thndr: '#fbff00'
