# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version: 2
final_space: true
console_title_template: "{{ .Shell }} in {{ .Folder }}"
blocks:
- type: prompt
  alignment: left
  newline: true
  segments:
  - type: session
    style: powerline
    template: "{{ if .SSHSession }}\ueba9 {{ .UserName }}@{{ .HostName }}{{ end }}"
    background: yellow
    foreground: black
  - type: path
    style: powerline
    powerline_symbol: 
    template: " \uea83 {{ .Path }} "
    properties:
      style: agnoster_short
      max_depth: 3
    background: p:orange
    foreground: white
  - type: git
    style: powerline
    powerline_symbol: 
    template: "{{ .HEAD }}{{ if .Behind }}\u21e3{{ end }}{{ if .Ahead }}\u21e1{{ end }}{{ if .Working.Changed }} \uf044 {{ end }}{{ if .Staging.Changed }}\uf046{{ end }} "
    properties:
      branch_max_length: 25
      fetch_status: true
      fetch_upstream_icon: true
    background: green
    foreground: black
    text: ""
    duration: 0s
    namelength: 0
- type: prompt
  alignment: right
  overflow: hide
  segments:
  - type: node
    style: plain
    template: "\ue718 "
    properties:
      display_mode: files
      fetch_package_manager: false
      home_enabled: false
    background: transparent
    foreground: green
  - type: go
    style: plain
    template: "\ue626 "
    properties:
      fetch_version: false
    background: transparent
    foreground: p:blue
  - type: python
    style: plain
    template: "\ue235 "
    properties:
      display_mode: files
      fetch_version: false
      fetch_virtual_env: false
    background: transparent
    foreground: yellow
  - type: executiontime
    style: plain
    foreground: yellow
    background: transparent
    template: " <#fefefe></> {{ .FormattedMs }} "
    properties:
      threshold: 500
      style: round
      # always_enabled: true
- type: prompt
  alignment: left
  newline: true
  segments:
  - type: root
    style: plain
    powerline_symbol: 
    template: "\uf0e7"
    background: red
    foreground: white
  - type: status
    style: plain
    foreground_templates:
    - "{{ if gt .Code 0 }}red{{ end }}"
    - "{{ if eq .Code 0 }}green{{ end }}"
    template: "\u276f"
    properties:
      always_enabled: true
    background: transparent
    foreground: blue
tooltips:
- type: aws
  tips:
  - aws
  style: diamond
  leading_diamond: 
  trailing_diamond: 
  template: " \ue7ad {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} "
  properties:
    display_default: true
  background: p:orange
  foreground: p:white
  text: ""
  duration: 0s
  namelength: 0
- type: az
  tips:
  - az
  style: diamond
  leading_diamond: 
  trailing_diamond: 
  template: " \uebd8 {{ .Name }} "
  properties:
    display_default: true
  background: p:blue
  foreground: p:white
  text: ""
  duration: 0s
  namelength: 0
transient_prompt:
  template: "❯ "
  background: transparent
  foreground: blue
  text: ""
  duration: 0s
  namelength: 0
secondary_prompt:
  template: |
    {{ if eq .Shell "pwsh" }}>{{ else }}\u276f {{ end }}
  background: transparent
  foreground: darkGray
palette:
  black: "#262B44"
  blue: "#4B95E9"
  green: "#59C9A5"
  orange: "#F07623"
  red: "#D81E5B"
  white: "#E0DEF4"
  yellow: "#F3AE35"
